export const LIST_EMPLOYEE_REQUEST = "LIST_EMPLOYEE_REQUEST";
export const LIST_EMPLOYEE_SUCCESS = "LIST_EMPLOYEE_SUCCESS";
export const LIST_EMPLOYEE_FAIL = "LIST_EMPLOYEE_FAIL";

export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const REMOVE_EMPLOYEE = "REMOVE_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
